spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"
              allow-credentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          filters:
            AuthenticationFilter

          predicates:
            - Path=/api/v1/auth/**
        - id: course-service
          uri: lb://course-service
          filters:
            AuthenticationFilter
          predicates:
            - Path=/api/v1/course/**

        - id: authorisation-service
          uri: lb://authorisation-service
          filters:
             AuthenticationFilter
          predicates:
            - Path=/api/v1/authorisation/**

server:
  port: 8001
